[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault_program = "G5SqEevGbZ8GY7Yge9yvUybwA9ScD6RrVwL8utaQXY9v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
